### ISSUE TITLE
Need to get Paste working

### ISSUE THREAD

**Issue by concat** [dabonetn/linapple-pie#13]
This functionality is commented out in the keyboard code. Can it be implemented please? Needed for some software development.

**Comment by dabonetn** [comment]
I suggest looking at this version, it has much more active development.

https://github.com/linappleii/linapple

My fork was just adding joystick config and disk mapping from the command line.

**Comment by concat** [comment]
Thanks. I am working on bringing your fork up to SDL 2.0 and taking
advantage of SDL clipboard support.
