### ISSUE TITLE
Can this be installed on Pi400

### ISSUE THREAD

**Issue by Ernisius** [dabonetn/linapple-pie#14]
When I try I get the message 'error while loading shared libraries: libzip.so.2'
I installed libzip-dev

**Comment by dabonetn** [comment]
I don't have a pi400, but it does compile on a pi4 using the latest release of retropie. This version says it's compatible with the pi400 also.
Use the retropie-setup to install it from source.
It doesn't seem to go full screen, but I think that's a PI4 video driver issue.
But you can edit your /home/pi/.linapple/linapple.conf and change screen height and width to match your monitor.
