### ISSUE TITLE
feature: volume preference

### ISSUE THREAD

**Issue by rhaleblian** [dabonetn/linapple-pie#5]
Add a configuration pair for setting the volume in SDL (provided that's possible).

Retropie exposes `alsamixer`, but that's an OS master volume, and the emulators are of different loudness. When the Apple II spits huge transients out, if they're loud it could damage speakers (cringing over here). I figure the code that halves the `#define`d MAX VOLUME speaks to that.

**Comment by dabonetn** [comment]
My branch only took the original and added support to mount disk and map joysticks. These are things that are beyond me, and it seems beotiger hasn't updated in quite a while. (The only working download for linapple off the sourceforge page seems to be mine.)

You can see if you can contact him for this at http://linapple.sourceforge.net/index.html
